# Generated by Django 4.0.2 on 2022-02-18 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_favorite_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
