# Generated by Django 4.0.2 on 2022-03-10 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_product_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='numReviews',
        ),
    ]
