# Generated by Django 4.2.7 on 2023-11-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_product_countinstock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count_inStock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
