# Generated by Django 4.0.2 on 2022-02-20 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_shippingaddress_review_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='email',
        ),
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
    ]
